name: "Library Lint ğŸŸ â­ï¸â­ï¸â­ï¸â­ï¸ Dragon Ball"

on:
  pull_request:
    branches: [ master, develop, release/*, feature/*, hotfix/* ]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GO_VERSION: "1.24.x"

jobs:
  golangci:
    name: "Run Lint ğŸŸ â­ï¸â­ï¸â­ï¸â­ï¸"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - run: make deps || true
      - run: make tidy || true
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7
          args: ./...
